apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana-example
  annotations:
    kubectl.kubernetes.io/server-side: "true"
namespace: observe
buildMetadata:
- originAnnotations
resources:
- queries.yaml
- constants.yaml
generators:
- panels/up.yaml
- panels/note.yaml
transformers:
- panels/cpu.yaml
- dashboard.yaml
- folder.yaml
