# A local text panel whose content is a file.
apiVersion: grafana.krm.kubed.io/v1alpha1
kind: Panel
metadata:
  name: note
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: kubectl-kubed
spec:
  title: ''
  transparent: true
  vizConfig:
    kind: VizConfig
    group: text
    spec:
      options:
        mode: html
        content:
          kind: Embed
          spec:
            file: note.html
