kind: RowsLayoutRow
spec:
  title: Overview
  layout:
    kind: GridLayout
    spec:
      items:
      - kind: GridLayoutItem
        spec:
          x: 0
          y: 0
          width: 12
          height: 6
          element:
            kind: ElementReference
            name: up
      - kind: GridLayoutItem
        spec:
          x: 12
          y: 0
          width: 12
          height: 6
          element:
            kind: ElementReference
            name: example-cpu
