name: 📸 Image Builder

on:
  workflow_dispatch: {}
  workflow_call: 
    inputs:
      push:
        description: Whether to push the image to DockerHub
        default: true
        type: boolean
    secrets:
      DOCKER_USERNAME:
        description: Docker username
        required: true
      DOCKER_PASSWORD:
        description: Docker password
        required: true

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    environment: 
      name: dockerhub
      url: https://hub.docker.com/r/kubed/krm-py
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup QEMU
      id: setup-qemu
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Image Args
      run: |
        {
          echo "GIT_REF=$(echo ${GITHUB_REF##*/} | sed -e 's/\//_/g')";
          echo "GIT_SHA=$(git rev-parse --short HEAD)";
          echo "PY_VERSION=$(cat .python-version)";
        } >> $GITHUB_ENV
      
    - name: Login to DockerHub
      id: login-dockerhub
      if: inputs.push && startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      env:
        PUSH_FLAG: ${{ inputs.push && startsWith(github.ref, 'refs/tags/v') && '--push' || '' }}
      run: docker buildx bake $PUSH_FLAG
