name: 📦 Publish

on:
  push:
    tags:
    - 'v*'

permissions:
  id-token: write

jobs:

  package:
    name: Publish
    uses: ./.github/workflows/package.yml
    
  image:
    name: Publish
    uses: ./.github/workflows/image.yml
    secrets: inherit
